<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class MigrateBenPersonalDetails extends Command
{
    protected $signature = 'migrate:ben-personal-details';
    protected $description = 'Migrate draft & faulty ben personal details to main table';

    public function handle()
    {
        DB::beginTransaction();

        try {

            /**
             * =====================================
             * DRAFT → MAIN
             * =====================================
             */
            DB::statement("
                INSERT INTO lb_scheme.ben_personal_details (
                    application_id,
                    ben_fname, ben_mname, ben_lname,
                    gender, dob, age_ason_01012021,
                    caste, marital_status,
                    father_fname, father_mname, father_lname,
                    mother_fname, mother_mname, mother_lname,
                    spouse_fname, spouse_mname, spouse_lname,
                    pension_amount, ss_card_no, mobile_no,
                    scheme_id,
                    created_by_dist_code, created_by_level, created_by_local_body_code,
                    created_at, updated_at, deleted_at,
                    created_by, ip_address,
                    ss_ben_id, caste_certificate_no, aadhar_no,
                    next_level_role_id, rejected_cause,
                    ss_full_name, comments,
                    duare_sarkar_registration_no, duare_sarkar_date,
                    email,
                    is_migrated,
                    is_faulty,
                    ds_phase,
                    eariler_rejected, real_created_at,
                    entry_type,
                    caste_certificate_validation_message,
                    wbpds_family_id, wbpds_ration_card_no, wbpds_name_as_in_aadhar,
                    wbpds_is_sent,
                    acc_validated_aadhar,
                    name_is_match,
                    aadhaar_no_checked,
                    aadhaar_no_checked_lastdatetime,
                    aadhaar_no_checked_pass,
                    aadhaar_no_validation_msg,
                    dob_kh, dob_is_match_kh,
                    action_by, action_ip_address, action_type,
                    ds_mark_ix, ds_marking_date,
                    sm_flag, cmo_mark, cmo_entry, cmo_grievance_id,
                    ds_phase_mark,
                    source_type               
                )
                SELECT
                    d.application_id,
                    d.ben_fname, d.ben_mname, d.ben_lname,
                    d.gender, d.dob, d.age_ason_01012021,
                    d.caste, d.marital_status,
                    d.father_fname, d.father_mname, d.father_lname,
                    d.mother_fname, d.mother_mname, d.mother_lname,
                    d.spouse_fname, d.spouse_mname, d.spouse_lname,
                    d.pension_amount, d.ss_card_no, d.mobile_no,
                    d.scheme_id,
                    d.created_by_dist_code, d.created_by_level, d.created_by_local_body_code,
                    d.created_at, d.updated_at, d.deleted_at,
                    d.created_by, d.ip_address,
                    d.ss_ben_id, d.caste_certificate_no, d.aadhar_no,
                    d.next_level_role_id, d.rejected_cause,
                    d.ss_full_name, d.comments,
                    d.duare_sarkar_registration_no, d.duare_sarkar_date,
                    d.email,
                    NULL AS is_migrated,
                    d.is_faulty,
                    d.ds_phase,
                    d.eariler_rejected,
                    NULL AS real_created_at,
                    d.entry_type,
                    d.caste_certificate_validation_message,
                    d.wbpds_family_id, d.wbpds_ration_card_no, d.wbpds_name_as_in_aadhar,
                    d.wbpds_is_sent,
                    d.acc_validated_aadhar,
                    d.name_is_match,
                    d.aadhaar_no_checked,
                    d.aadhaar_no_checked_lastdatetime,
                    d.aadhaar_no_checked_pass,
                    d.aadhaar_no_validation_msg,
                    d.dob_kh, d.dob_is_match_kh,
                    d.action_by, d.action_ip_address, d.action_type,
                    d.ds_mark_ix, d.ds_marking_date,
                    d.sm_flag, d.cmo_mark, d.cmo_entry, d.cmo_grievance_id,
                    d.ds_phase_mark,
                    1 AS source_type    
                FROM lb_scheme.draft_ben_personal_details d
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM lb_scheme.ben_personal_details b
                    WHERE b.application_id = d.application_id
                )
            ");



            /**
             * =====================================
             * FAULTY → MAIN
             * =====================================
             */
            DB::statement("
                INSERT INTO lb_scheme.ben_personal_details (
                    application_id,
                    ben_fname, ben_mname, ben_lname,
                    gender, dob, age_ason_01012021,
                    caste, marital_status,
                    father_fname, father_mname, father_lname,
                    mother_fname, mother_mname, mother_lname,
                    spouse_fname, spouse_mname, spouse_lname,
                    pension_amount, ss_card_no, mobile_no,
                    scheme_id,
                    created_by_dist_code, created_by_level, created_by_local_body_code,
                    created_at, updated_at, deleted_at,
                    created_by, ip_address,
                    ss_ben_id, caste_certificate_no, aadhar_no,
                    next_level_role_id, rejected_cause,
                    ss_full_name, comments,
                    duare_sarkar_registration_no, duare_sarkar_date,
                    email,
                    is_faulty, ds_phase,
                    real_created_at,
                    caste_matched_with_certificate_no,
                    life_certificate_checked, life_certificate_pass,
                    life_certificate_lastdatetime, last_biometric,
                    caste_certificate_check_lastdatetime, caste_certificate_checked,
                    no_aadhar, no_aadhar_next_level_role_id, pre_no_aadhar,
                    life_certificate_msg,
                    caste_certificate_validation_message,
                    wbpds_family_id, wbpds_ration_card_no, wbpds_name_as_in_aadhar,
                    wbpds_is_sent,
                    acc_validated_aadhar,
                    name_is_match,
                    aadhaar_no_checked,
                    aadhaar_no_checked_lastdatetime,
                    aadhaar_no_checked_pass,
                    aadhaar_no_validation_msg,
                    dob_kh, dob_is_match_kh,
                    entry_type,
                    action_by, action_ip_address, action_type,
                    ds_mark_ix, ds_marking_date,
                    sm_flag, cmo_mark, cmo_entry, cmo_grievance_id,
                    ds_phase_mark,
                    source_type               
                )
                SELECT
                    f.application_id,
                    f.ben_fname, f.ben_mname, f.ben_lname,
                    f.gender, f.dob, f.age_ason_01012021,
                    f.caste, f.marital_status,
                    f.father_fname, f.father_mname, f.father_lname,
                    f.mother_fname, f.mother_mname, f.mother_lname,
                    f.spouse_fname, f.spouse_mname, f.spouse_lname,
                    f.pension_amount, f.ss_card_no, f.mobile_no,
                    f.scheme_id,
                    f.created_by_dist_code, f.created_by_level, f.created_by_local_body_code,
                    f.created_at, f.updated_at, f.deleted_at,
                    f.created_by, f.ip_address,
                    f.ss_ben_id, f.caste_certificate_no, f.aadhar_no,
                    f.next_level_role_id, f.rejected_cause,
                    f.ss_full_name, f.comments,
                    f.duare_sarkar_registration_no, f.duare_sarkar_date,
                    f.email,
                    f.is_faulty, f.ds_phase,
                    NULL AS real_created_at,
                    f.caste_matched_with_certificate_no,
                    f.life_certificate_checked, f.life_certificate_pass,
                    f.life_certificate_lastdatetime, f.last_biometric,
                    f.caste_certificate_check_lastdatetime, f.caste_certificate_checked,
                    f.no_aadhar, f.no_aadhar_next_level_role_id, f.pre_no_aadhar,
                    f.life_certificate_msg,
                    NULL AS caste_certificate_validation_message,
                    f.wbpds_family_id, f.wbpds_ration_card_no, f.wbpds_name_as_in_aadhar,
                    NULL AS wbpds_is_sent,
                    f.acc_validated_aadhar,
                    NULL AS name_is_match,
                    f.aadhaar_no_checked,
                    f.aadhaar_no_checked_lastdatetime,
                    f.aadhaar_no_checked_pass,
                    f.aadhaar_no_validation_msg,
                    f.dob_kh, f.dob_is_match_kh,
                    f.entry_type,
                    f.action_by, f.action_ip_address, f.action_type,
                    f.ds_mark_ix, f.ds_marking_date,
                    f.sm_flag, f.cmo_mark,
                    NULL AS cmo_entry, NULL AS cmo_grievance_id,
                    f.ds_phase_mark,
                    2 AS source_type     
                FROM lb_scheme.faulty_ben_personal_details f
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM lb_scheme.ben_personal_details b
                    WHERE b.application_id = f.application_id
                )
            ");
            DB::statement("
                INSERT INTO lb_scheme.ben_personal_details (
                    application_id,
                    beneficiary_id,
                    ben_fname, ben_mname, ben_lname,
                    gender, dob, age_ason_01012021,
                    caste, marital_status,
                    father_fname, father_mname, father_lname,
                    mother_fname, mother_mname, mother_lname,
                    spouse_fname, spouse_mname, spouse_lname,
                    pension_amount, ss_card_no, mobile_no,
                    scheme_id,
                    created_by_dist_code, created_by_level, created_by_local_body_code,
                    created_at, updated_at, deleted_at,
                    created_by, ip_address,
                    ss_ben_id, caste_certificate_no, aadhar_no,
                    next_level_role_id, rejected_cause,
                    ss_full_name, comments,
                    duare_sarkar_registration_no, duare_sarkar_date,
                    email,
                    sms_is_send,
                    approved_at,
                    is_migrated,
                    status,
                    is_faulty,
                    ds_phase,
                    is_caste_changed,
                    effective_yymm,
                    approval_date,
                    eariler_rejected,
                    is_aadhar_dup,
                    is_sent_jb,
                    is_migrated_jb,
                    real_created_at,
                    marked_data,
                    jnmp_marked,
                    jnmp_remarks,
                    acc_validated_aadhaar_new,
                    failed_process_type_aadhaar,
                    wbpds_name_as_in_aadhar,
                    process_acc_validated_aadhar,
                    acc_validated_aadhar,
                    next_level_role_id_aadhar_validation,
                    wrong_dob,
                    jb_dob,
                    next_level_role_id_dob,
                    new_dob,
                    wbpds_name_as_in_aadhar_sr,
                    name_is_match_sr,
                    caste_matched_with_certificate_no,
                    life_certificate_checked,
                    life_certificate_pass,
                    life_certificate_lastdatetime,
                    last_biometric,
                    caste_certificate_check_lastdatetime,
                    caste_certificate_checked,
                    no_aadhar,
                    no_aadhar_next_level_role_id,
                    pre_no_aadhar,
                    life_certificate_msg,
                    entry_type,
                    dup_id,
                    bio_aadhar_checked_api_failed,
                    wbpds_ration_card_no,
                    srs_rcc_category,
                    caste_certificate_validation_message,
                    wbpds_is_sent,
                    name_is_match,
                    aadhaar_no_checked,
                    aadhaar_no_checked_lastdatetime,
                    aadhaar_no_checked_pass,
                    aadhaar_no_validation_msg,
                    dob_kh,
                    dob_is_match_kh,
                    wbpds_family_id,
                    srs_name_as_in_aadhar_cur,
                    srs_dob,
                    reactive_reason,
                    is_samadhan,
                    old_aadhar_no,
                    similarity_percentage,
                    grade,
                    srs_ration_card_no,
                    srs_family_id,
                    migrated_to_srs,
                    action_by,
                    action_ip_address,
                    action_type,
                    payment_suspended,
                    ds_mark_ix,
                    ds_marking_date,
                    sm_flag,
                    cmo_mark,
                    cmo_entry,
                    cmo_grievance_id,
                    ds_phase_mark,
                    source_type
                )
                SELECT
                    b.application_id,
                    b.beneficiary_id,
                    b.ben_fname, b.ben_mname, b.ben_lname,
                    b.gender, b.dob, b.age_ason_01012021,
                    b.caste, b.marital_status,
                    b.father_fname, b.father_mname, b.father_lname,
                    b.mother_fname, b.mother_mname, b.mother_lname,
                    b.spouse_fname, b.spouse_mname, b.spouse_lname,
                    b.pension_amount, b.ss_card_no, b.mobile_no,
                    b.scheme_id,
                    b.created_by_dist_code, b.created_by_level, b.created_by_local_body_code,
                    b.created_at, b.updated_at, b.deleted_at,
                    b.created_by, b.ip_address,
                    b.ss_ben_id, b.caste_certificate_no, b.aadhar_no,
                    b.next_level_role_id, b.rejected_cause,
                    b.ss_full_name, b.comments,
                    b.duare_sarkar_registration_no, b.duare_sarkar_date,
                    b.email,
                    b.sms_is_send,
                    b.approved_at,
                    b.is_migrated,
                    b.status,
                    b.is_faulty,
                    b.ds_phase,
                    b.is_caste_changed,
                    b.effective_yymm,
                    b.approval_date,
                    b.eariler_rejected,
                    b.is_aadhar_dup,
                    b.is_sent_jb,
                    b.is_migrated_jb,
                    b.real_created_at,
                    b.marked_data,
                    b.jnmp_marked,
                    b.jnmp_remarks,
                    b.acc_validated_aadhaar_new,
                    b.failed_process_type_aadhaar,
                    b.wbpds_name_as_in_aadhar,
                    b.process_acc_validated_aadhar,
                    b.acc_validated_aadhar,
                    b.next_level_role_id_aadhar_validation,
                    b.wrong_dob,
                    b.jb_dob,
                    b.next_level_role_id_dob,
                    b.new_dob,
                    b.wbpds_name_as_in_aadhar_sr,
                    b.name_is_match_sr,
                    b.caste_matched_with_certificate_no,
                    b.life_certificate_checked,
                    b.life_certificate_pass,
                    b.life_certificate_lastdatetime,
                    b.last_biometric,
                    b.caste_certificate_check_lastdatetime,
                    b.caste_certificate_checked,
                    b.no_aadhar,
                    b.no_aadhar_next_level_role_id,
                    b.pre_no_aadhar,
                    b.life_certificate_msg,
                    b.entry_type,
                    b.dup_id,
                    b.bio_aadhar_checked_api_failed,
                    b.wbpds_ration_card_no,
                    b.srs_rcc_category,
                    b.caste_certificate_validation_message,
                    b.wbpds_is_sent,
                    b.name_is_match,
                    b.aadhaar_no_checked,
                    b.aadhaar_no_checked_lastdatetime,
                    b.aadhaar_no_checked_pass,
                    b.aadhaar_no_validation_msg,
                    b.dob_kh,
                    b.dob_is_match_kh,
                    b.wbpds_family_id,
                    b.srs_name_as_in_aadhar_cur,
                    b.srs_dob,
                    b.reactive_reason,
                    b.is_samadhan,
                    b.old_aadhar_no,
                    b.similarity_percentage,
                    b.grade,
                    b.srs_ration_card_no,
                    b.srs_family_id,
                    b.migrated_to_srs,
                    b.action_by,
                    b.action_ip_address,
                    b.action_type,
                    b.payment_suspended,
                    b.ds_mark_ix,
                    b.ds_marking_date,
                    b.sm_flag,
                    b.cmo_mark,
                    b.cmo_entry,
                    b.cmo_grievance_id,
                    b.ds_phase_mark,
                    0 AS source_type
                FROM lb_scheme.ben_personal b
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM lb_scheme.ben_personal_details d
                    WHERE d.application_id = b.application_id
                )
            ");
            DB::commit();
        } catch (\Throwable $e) {
            DB::rollBack();
            throw $e;
        }
    }
}
