<?php

namespace Database\Seeders\Role;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tableNames = config('permission.table_names');
        DB::table($tableNames['roles'])->truncate();
        DB::table($tableNames['permissions'])->truncate();
        DB::table($tableNames['model_has_permissions'])->truncate();
        DB::table($tableNames['model_has_roles'])->truncate();
        DB::table($tableNames['role_has_permissions'])->truncate();
        // Reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $roles = [
            'Super Admin',
            'HOD',
            'Delegated HOD',
            'Approver',
            'Delegated Approver',
            'Verifier',
            'Delegated Verifier',
            'Operator',
            'Delegated Operator',
            'DDO',
            'Delegated DDO',
            'Mis User State',
            'Mis User District',
            'Mis User Block',
            'Mis User GP',
            'Mis User Sub Division',
            'Mis User Municipality',
            'Mis User Ward',
        ];
        $can_roles_manages = [
            'Super Admin' => ['HOD', 'Delegated HOD', 'Approver', 'Delegated Approver', 'Checker', 'Delegated Checker', 'Maker', 'Delegated Maker',
                'DDO', 'Delegated DDO', 'Mis User State', 'Mis User District', 'Mis User Block', 'Mis User GP',
                'Mis User Sub Division', 'Mis User Municipality', 'Mis User Ward'],

            'HOD' => ['Delegated HOD', 'Approver', 'Delegated Approver', 'Checker', 'Delegated Checker', 'Maker', 'Delegated Maker',
                'DDO', 'Delegated DDO', 'Mis User State', 'Mis User District', 'Mis User Block', 'Mis User GP',
                'Mis User Sub Division', 'Mis User Municipality', 'Mis User Ward'],
            'Delegated HOD' => '',
            'Approver' => ['Delegated Approver', 'Checker', 'Delegated Checker', 'Maker', 'Delegated Maker',
                'DDO', 'Delegated DDO', 'Mis User District', 'Mis User Block', 'Mis User GP',
                'Mis User Sub Division', 'Mis User Municipality', 'Mis User Ward'],
            'Delegated Approver' => '',
            'Checker' => ['Delegated Checker', 'Maker', 'Delegated Maker',
                'DDO', 'Delegated DDO', 'Mis User Block', 'Mis User GP',
                'Mis User Sub Division', 'Mis User Municipality', 'Mis User Ward'],
            'Delegated Checker' => '',
            'Maker' => '',
            'Delegated Maker' => '',
            'DDO' => '',
            'Delegated DDO' => '',
            'Mis User State' => '',
            'Mis User District' => '',
            'Mis User Block' => '',
            'Mis User GP' => '',
            'Mis User Sub Division' => '',
            'Mis User Municipality' => '',
            'Mis User Ward' => '',
        ];

        $permissions = [
            // Validation Lot
            'create validation lot',
            'push validation lot',
            'ack validation lot',
            'get validation lot response',
            'import validation lot response',
            // Payment  Lot SBI
            'create payment lot SBI',
            'sign payment lot SBI',
            'push payment lot SBI',
            'ack payment lot SBI',
            'get payment lot response SBI',
            'import payment lot response SBI',

            // Payment  Lot IFMS
            'create payment lot IFMS',
            'push payment lot IFMS',
            'ack payment lot IFMS',
            'submit to tresury IFMS',
            'sent to rbi IFMS',
            'get payment lot response IFMS',

            // User Model
            'create user',
            'read user',
            'update user',
            'delete user',

            // Role
            'create role',
            'read role',
            'update role',
            'delete role',
            // Permission
            'create permission',
            'read permission',
            'update permission',
            'delete permission',
            // Role Permission
            'create role permission',
            'read role permission',
            'update role permission',
            'delete role permission',
            // User Role
            'create user role',
            'read user role',
            'update user role',
            'delete user role',
            // User Permission
            'create user permission',
            'read user permission',
            'update user permission',
            'delete user permission',
            // State
            'create state',
            'read state',
            'update state',
            'delete state',
            // District
            'create district',
            'read district',
            'update district',
            'delete district',
            // Block
            'create block',
            'read block',
            'update block',
            'delete block',
            // Gp
            'create gp',
            'read gp',
            'update gp',
            'delete gp',
            // Municipality
            'create municipality',
            'read municipality',
            'update municipality',
            'delete municipality',
            // Ward
            'create ward',
            'read ward',
            'update ward',
            'delete ward',
            // Workflow
            'application list',
            'application view',
            'application entry',
            'application verify',
            'application approve',
            'application revert',
            'application reject',
            'application bulk approval',
            'application recommanded',
            'application recommanded bulk',
            'application entryverifyapproval',
            // Add your new permissions here
            'update bank',
            'search bank update',
            'update mobile',
            'view beneficiary details',
            'update bank details',
            'submit lb form',
            'view draft list',
            'edit draft',
            'view lb applications',
            'view application',
            'view beneficiaries',
            'revert incomplete',
            'manage role mappings',
            'create users',
            'create role mappings',
            'view offices',
            'view reports',
            'update caste',
            'edit caste',
            'view approved ba wise',
            'view approved list',
            'modify caste',
            'view caste modification list',
            'view incomplete applications',
            'view users',
            'update incomplete',
            'view verifier incomplete',
            'view approver incomplete',
            'view permission',
            'view user permission',
            'create offices',
            'update-mark-beneficiary-details',
            'update-beneficiary-list',
            'request-update-beneficiary',
            'Duare Sarkar Entry',
            'Normal Entry',
            'submit-lb-form',
            'Normal Entry Verification Allow',
            'Normal Entry Approver Allow',
            'Normal Entry Reject Allow',
            'Normal Entry Revert Allow',
            'Bulk Actions Normal Entry Verification Allow',
            'Bulk Actions Normal Entry Approver Allow',
            'Bulk Actions Normal Entry Reject Allow',
            'Bulk Actions Normal Entry Revert Allow',
            'Duare Sarkar Entry Verification Allow',
            'Duare Sarkar Entry Approver Allow',
            'Duare Sarkar Entry Reject Allow',
            'Duare Sarkar Entry Revert Allow',
            'Bulk Actions Duare Sarkar Entry Verification Allow',
            'Bulk Actions Duare Sarkar Entry Approver Allow',
            'Bulk Actions Duare Sarkar Entry Reject Allow',
            'Bulk Actions Duare Sarkar Entry Revert Allow',
            'TakeActionForCaste',
            'VerifyCasteApplication',
            'ApproveCasteApplication',
            'RevertCasteApplication',
            'RejectApprovedBeneficiary',
            'Filter Applicant To Reject',
            'View Details To Reject',
            'Reject Beneficiary',
            'back-from-jb',
            'back-from-jb-verifier-button',
            'back-from-jb-approver-button',
            'sarasori-mukhyamantri',
            'cmo-grievance-mark',
            'viewlb applications',
            'lb-application-list',
            're-activate-death-incident',
            'manage-menus',
            'manage-permissions',
            'manage-roles',
            'manage-users',
            'manage-departments',
            'manage-schemes',
            'RolePermissionManagement',
            'UserManagement',
            'DutyAssignManagement',
            'OfficeManagement',
            'scheme-capacity-setting',
            'import-janma-mrityu-data',
            'dynamic-workflow-management',
            'cmo-data-fetch',
            'master-tab',
            'role-rank-management',
            'define-workflow',
            'role-permission-management',
        ];
        $rolesArr = collect($roles)->map(function ($role) {
            return [
                'name' => $role,
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        })->toArray();
        $permissionsArr = collect($permissions)->map(function ($permission) {
            return [
                'name' => $permission,
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        })->toArray();

        Role::insert($rolesArr);
        Permission::insert($permissionsArr);

        $role_permission_map = [
            'Super Admin' => [
                // User Model
                'create user',
                'read user',
                'update user',
                'delete user',
                // Role
                'create role',
                'read role',
                'update role',
                'delete role',
                // Permission
                'create permission',
                'read permission',
                'update permission',
                'delete permission',
                // Role Permission
                'create role permission',
                'read role permission',
                'update role permission',
                'delete role permission',
                'RolePermissionManagement',
                'UserManagement',
                'DutyAssignManagement',
                'OfficeManagement',
                'create role mappings',
                'manage role mappings',
                'view offices',
                'create offices',
                'view users',
                'create users',
                'view user permission',
                'view permission',
                'master-tab',
                'role-rank-management',
                'define-workflow',
                'role-permission-management',
                'scheme-capacity-setting',
                'import-janma-mrityu-data',
                'dynamic-workflow-management',
                'cmo-data-fetch',
            ],
            'HOD' => [
                // Workflow
                'application list',
                'application view',
                'application recommanded',
                'application recommanded bulk',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'Delegated HOD' => [
                // Workflow
                'application list',
                'application view',
                'application recommanded',
                'application recommanded bulk',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'Approver' => [
                // District
                'read district',
                // Block
                'read block',
                // Municipality
                'read municipality',
                // Workflow
                'application list',
                'application view',
                'application approve',
                'application revert',
                'application reject',
                'application bulk approval',
                'viewlb applications',
                'Normal Entry Approver Allow',
                'Normal Entry Reject Allow',
                'Normal Entry Revert Allow',
                'view beneficiaries',
                'view reports',
                'update bank details',
                'search bank update',
                'update mobile',
                'view approver incomplete',
                'view users',
                'create users',
                'view caste modification list',
                'view beneficiary details',
                'TakeActionForCaste',
                'ApproveCasteApplication',
                'RevertCasteApplication',
                'RejectApprovedBeneficiary',
                'Filter Applicant To Reject',
                'View Details To Reject',
                'Reject Beneficiary',
                'lb-application-list',
                'Bulk Actions Normal Entry Approver Allow',
                'Bulk Actions Normal Entry Reject Allow',
                'Bulk Actions Normal Entry Revert Allow',
                'Bulk Actions Duare Sarkar Entry Approver Allow',
                'Bulk Actions Duare Sarkar Entry Reject Allow',
                'Bulk Actions Duare Sarkar Entry Revert Allow',
                'Duare Sarkar Entry Approver Allow',
                'Duare Sarkar Entry Reject Allow',
                'Duare Sarkar Entry Revert Allow',
                're-activate-death-incident',
                'manage-menus',
                'manage-permissions',
                'manage-roles',
                'manage-users',
                'manage-departments',
                'manage-schemes',
                'modify caste',
                'back-from-jb',
                'back-from-jb-approver-button',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'Delegated Approver' => [
                // District
                'read district',
                // Block
                'read block',
                // Municipality
                'read municipality',
                // Workflow
                'application list',
                'application view',
                'application approve',
                'application revert',
                'application reject',
                'application bulk approval',
                'viewlb applications',
                'Normal Entry Approver Allow',
                'Normal Entry Reject Allow',
                'Normal Entry Revert Allow',
                'view beneficiaries',
                'view reports',
                'update bank details',
                'search bank update',
                'update mobile',
                'view approver incomplete',
                'view users',
                'create users',
                'view caste modification list',
                'view beneficiary details',
                'TakeActionForCaste',
                'ApproveCasteApplication',
                'RevertCasteApplication',
                'RejectApprovedBeneficiary',
                'Filter Applicant To Reject',
                'View Details To Reject',
                'Reject Beneficiary',
                'lb-application-list',
                'Bulk Actions Normal Entry Approver Allow',
                'Bulk Actions Normal Entry Reject Allow',
                'Bulk Actions Normal Entry Revert Allow',
                'Bulk Actions Duare Sarkar Entry Approver Allow',
                'Bulk Actions Duare Sarkar Entry Reject Allow',
                'Bulk Actions Duare Sarkar Entry Revert Allow',
                'Duare Sarkar Entry Approver Allow',
                'Duare Sarkar Entry Reject Allow',
                'Duare Sarkar Entry Revert Allow',
                're-activate-death-incident',
                'manage-menus',
                'manage-permissions',
                'manage-roles',
                'manage-users',
                'manage-departments',
                'manage-schemes',
                'modify caste',
                'back-from-jb',
                'back-from-jb-approver-button',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'Verifier' => [
                // District
                'read district',
                // Block
                'read block',
                // Municipality
                'read municipality',
                // Workflow
                'application list',
                'application view',
                'application verify',
                'application revert',
                'application reject',
                'Normal Entry Verification Allow',
                'Normal Entry Reject Allow',
                'Normal Entry Revert Allow',
                'view beneficiaries',
                'view reports',
                'view verifier incomplete',
                'view caste modification list',
                'view beneficiary details',
                'TakeActionForCaste',
                'VerifyCasteApplication',
                'RevertCasteApplication',
                'lb-application-list',
                'Bulk Actions Duare Sarkar Entry Verification Allow',
                'Bulk Actions Duare Sarkar Entry Reject Allow',
                'Bulk Actions Duare Sarkar Entry Revert Allow',
                'Duare Sarkar Entry Reject Allow',
                'Duare Sarkar Entry Verification Allow',
                'Duare Sarkar Entry Revert Allow',
                'Bulk Actions Normal Entry Revert Allow',
                'Bulk Actions Normal Entry Reject Allow',
                'Bulk Actions Normal Entry Verification Allow',
                'modify caste',
                'back-from-jb',
                'back-from-jb-verifier-button',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'Delegated Verifier' => [
                // District
                'read district',
                // Block
                'read block',
                // Municipality
                'read municipality',
                // Workflow
                'application list',
                'application view',
                'application verify',
                'application revert',
                'application reject',
                'Normal Entry Verification Allow',
                'Normal Entry Reject Allow',
                'Normal Entry Revert Allow',
                'view beneficiaries',
                'view reports',
                'view verifier incomplete',
                'view caste modification list',
                'view beneficiary details',
                'TakeActionForCaste',
                'VerifyCasteApplication',
                'RevertCasteApplication',
                'lb-application-list',
                'Bulk Actions Duare Sarkar Entry Verification Allow',
                'Bulk Actions Duare Sarkar Entry Reject Allow',
                'Bulk Actions Duare Sarkar Entry Revert Allow',
                'Duare Sarkar Entry Reject Allow',
                'Duare Sarkar Entry Verification Allow',
                'Duare Sarkar Entry Revert Allow',
                'Bulk Actions Normal Entry Revert Allow',
                'Bulk Actions Normal Entry Reject Allow',
                'Bulk Actions Normal Entry Verification Allow',
                'modify caste',
                'back-from-jb',
                'back-from-jb-verifier-button',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'Operator' => [
                // District
                'read district',
                // Block
                'read block',
                // Municipality
                'read municipality',
                // Workflow
                'application view',
                'application list',
                'application entry',
                'view draft list',
                'edit draft',
                'view beneficiaries',
                'view reports',
                'Duare Sarkar Entry',
                'Normal Entry',
                'submit-lb-form',
                'view caste modification list',
                'edit caste',
                'update caste',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'Delegated Operator' => [
                // District
                'read district',
                // Block
                'read block',
                // Municipality
                'read municipality',
                // Workflow
                'application view',
                'application list',
                'application entry',
                'view draft list',
                'edit draft',
                'view beneficiaries',
                'view reports',
                'Duare Sarkar Entry',
                'Normal Entry',
                'submit-lb-form',
                'view caste modification list',
                'edit caste',
                'update caste',
                'sarasori-mukhyamantri',
                'cmo-grievance-mark',
            ],
            'DDO' => [
                // Validation Lot
                'create validation lot',
                'push validation lot',
                'ack validation lot',
                'get validation lot response',
                'import validation lot response',
                // Payment  Lot SBI
                'create payment lot SBI',
                'sign payment lot SBI',
                'push payment lot SBI',
                'ack payment lot SBI',
                'get payment lot response SBI',
                'import payment lot response SBI',

                // Payment  Lot IFMS
                'create payment lot IFMS',
                'push payment lot IFMS',
                'ack payment lot IFMS',
                'submit to tresury IFMS',
                'sent to rbi IFMS',
                'get payment lot response IFMS',
            ],
            'Delegated DDO' => [
                // Validation Lot
                'create validation lot',
                'push validation lot',
                'ack validation lot',
                'get validation lot response',
                'import validation lot response',
                // Payment  Lot SBI
                'create payment lot SBI',
                'sign payment lot SBI',
                'push payment lot SBI',
                'ack payment lot SBI',
                'get payment lot response SBI',
                'import payment lot response SBI',

                // Payment  Lot IFMS
                'create payment lot IFMS',
                'push payment lot IFMS',
                'ack payment lot IFMS',
                'submit to tresury IFMS',
                'sent to rbi IFMS',
                'get payment lot response IFMS',
            ],
        ];

        foreach ($role_permission_map as $role_name => $permissions) {
            $role = Role::findByName($role_name);
            $role->givePermissionTo($permissions);
        }

    }
}
