<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class BenTransactionDetailsJB extends Model
{
    use Searchable;
    protected $connection = 'pgsql_jbpayread';
    protected $table = 'payment.ben_transaction_details';
    protected $primaryKey = 'id';
    public $incrementing = true;

    protected $fillable = [
        "dist_code",
        "ben_id",
        "scheme_id",
        "present_amt",
        "present_count",
        "apr_lot_no",
        "apr_lot_type",
        "apr_lot_status",
        "apr_is_eligible",
        "apr_eligible_amount",
        "apr_payment_amount",
        "may_lot_no",
        "may_lot_type",
        "may_lot_status",
        "may_is_eligible",
        "may_eligible_amount",
        "may_payment_amount",
        "jun_lot_no",
        "jun_lot_type",
        "jun_lot_status",
        "jun_is_eligible",
        "jun_eligible_amount",
        "jun_payment_amount",
        "jul_lot_no",
        "jul_lot_type",
        "jul_lot_status",
        "jul_is_eligible",
        "jul_eligible_amount",
        "jul_payment_amount",
        "aug_lot_no",
        "aug_lot_type",
        "aug_lot_status",
        "aug_is_eligible",
        "aug_eligible_amount",
        "aug_payment_amount",
        "sep_lot_no",
        "sep_lot_type",
        "sep_lot_status",
        "sep_is_eligible",
        "sep_eligible_amount",
        "sep_payment_amount",
        "oct_lot_no",
        "oct_lot_type",
        "oct_lot_status",
        "oct_is_eligible",
        "oct_eligible_amount",
        "oct_payment_amount",
        "nov_lot_no",
        "nov_lot_type",
        "nov_lot_status",
        "nov_is_eligible",
        "nov_eligible_amount",
        "nov_payment_amount",
        "dec_lot_no",
        "dec_lot_type",
        "dec_lot_status",
        "dec_is_eligible",
        "dec_eligible_amount",
        "dec_payment_amount",
        "jan_lot_no",
        "jan_lot_type",
        "jan_lot_status",
        "jan_is_eligible",
        "jan_eligible_amount",
        "jan_payment_amount",
        "feb_lot_no",
        "feb_lot_type",
        "feb_lot_status",
        "feb_is_eligible",
        "feb_eligible_amount",
        "feb_payment_amount",
        "mar_lot_no",
        "mar_lot_type",
        "mar_lot_status",
        "mar_is_eligible",
        "mar_eligible_amount",
        "mar_payment_amount",
        "start_yymm",
        "end_yymm",
        "fin_year",
        "local_body_code",
        "rural_urban_id",
        "block_ulb_code",
        "gp_ward_code",
        "payment_log",
        "created_at",
        "updated_at",
        "deleted_at"
    ];

    public function toSearchableArray()
    {
        return [
            "id" => $this->id,
            "dist_code" => $this->dist_code,
            "ben_id" => $this->ben_id,
            "scheme_id" => $this->scheme_id,
            "present_amt" => $this->present_amt,
            "present_count" => $this->present_count,
            "apr_lot_no" => $this->apr_lot_no,
            "apr_lot_type" => $this->apr_lot_type,
            "apr_lot_status" => $this->apr_lot_status,
            "apr_is_eligible" => $this->apr_is_eligible,
            "apr_eligible_amount" => $this->apr_eligible_amount,
            "apr_payment_amount" => $this->apr_payment_amount,
            "may_lot_no" => $this->may_lot_no,
            "may_lot_type" => $this->may_lot_type,
            "may_lot_status" => $this->may_lot_status,
            "may_is_eligible" => $this->may_is_eligible,
            "may_eligible_amount" => $this->may_eligible_amount,
            "may_payment_amount" => $this->may_payment_amount,
            "jun_lot_no" => $this->jun_lot_no,
            "jun_lot_type" => $this->jun_lot_type,
            "jun_lot_status" => $this->jun_lot_status,
            "jun_is_eligible" => $this->jun_is_eligible,
            "jun_eligible_amount" => $this->jun_eligible_amount,
            "jun_payment_amount" => $this->jun_payment_amount,
            "jul_lot_no" => $this->jul_lot_no,
            "jul_lot_type" => $this->jul_lot_type,
            "jul_lot_status" => $this->jul_lot_status,
            "jul_is_eligible" => $this->jul_is_eligible,
            "jul_eligible_amount" => $this->jul_eligible_amount,
            "jul_payment_amount" => $this->jul_payment_amount,
            "aug_lot_no" => $this->aug_lot_no,
            "aug_lot_type" => $this->aug_lot_type,
            "aug_lot_status" => $this->aug_lot_status,
            "aug_is_eligible" => $this->aug_is_eligible,
            "aug_eligible_amount" => $this->aug_eligible_amount,
            "aug_payment_amount" => $this->aug_payment_amount,
            "sep_lot_no" => $this->sep_lot_no,
            "sep_lot_type" => $this->sep_lot_type,
            "sep_lot_status" => $this->sep_lot_status,
            "sep_is_eligible" => $this->sep_is_eligible,
            "sep_eligible_amount" => $this->sep_eligible_amount,
            "sep_payment_amount" => $this->sep_payment_amount,
            "oct_lot_no" => $this->oct_lot_no,
            "oct_lot_type" => $this->oct_lot_type,
            "oct_lot_status" => $this->oct_lot_status,
            "oct_is_eligible" => $this->oct_is_eligible,
            "oct_eligible_amount" => $this->oct_eligible_amount,
            "oct_payment_amount" => $this->oct_payment_amount,
            "nov_lot_no" => $this->nov_lot_no,
            "nov_lot_type" => $this->nov_lot_type,
            "nov_lot_status" => $this->nov_lot_status,
            "nov_is_eligible" => $this->nov_is_eligible,
            "nov_eligible_amount" => $this->nov_eligible_amount,
            "nov_payment_amount" => $this->nov_payment_amount,
            "dec_lot_no" => $this->dec_lot_no,
            "dec_lot_type" => $this->dec_lot_type,
            "dec_lot_status" => $this->dec_lot_status,
            "dec_is_eligible" => $this->dec_is_eligible,
            "dec_eligible_amount" => $this->dec_eligible_amount,
            "dec_payment_amount" => $this->dec_payment_amount,
            "jan_lot_no" => $this->jan_lot_no,
            "jan_lot_type" => $this->jan_lot_type,
            "jan_lot_status" => $this->jan_lot_status,
            "jan_is_eligible" => $this->jan_is_eligible,
            "jan_eligible_amount" => $this->jan_eligible_amount,
            "jan_payment_amount" => $this->jan_payment_amount,
            "feb_lot_no" => $this->feb_lot_no,
            "feb_lot_type" => $this->feb_lot_type,
            "feb_lot_status" => $this->feb_lot_status,
            "feb_is_eligible" => $this->feb_is_eligible,
            "feb_eligible_amount" => $this->feb_eligible_amount,
            "feb_payment_amount" => $this->feb_payment_amount,
            "mar_lot_no" => $this->mar_lot_no,
            "mar_lot_type" => $this->mar_lot_type,
            "mar_lot_status" => $this->mar_lot_status,
            "mar_is_eligible" => $this->mar_is_eligible,
            "mar_eligible_amount" => $this->mar_eligible_amount,
            "mar_payment_amount" => $this->mar_payment_amount,
            "start_yymm" => $this->start_yymm,
            "end_yymm" => $this->end_yymm,
            "fin_year" => $this->fin_year,
            "local_body_code" => $this->local_body_code,
            "rural_urban_id" => $this->rural_urban_id,
            "block_ulb_code" => $this->block_ulb_code,
            "gp_ward_code" => $this->gp_ward_code,
            "payment_log" => $this->payment_log,
            "created_at" => $this->created_at,
            "updated_at" => $this->updated_at,
            "deleted_at" => $this->deleted_at
        ];
    }

    public function searchableAs()
    {
        return 'payment_ben_transaction_details_jbs';
    }
}
